In [1]:
import numpy as np

In [5]:
x = np.arange(-1.0, 1.01, 1.0)
y = np.arange(-2.0, 2.01, 1.0)
X, Y = np.meshgrid(x, y)
print(f'x = {x}')
print(f'y = {y}')
print(f'X = \n{X}')
print(f'Y = \n{Y}')


x = [-1.  0.  1.]
y = [-2. -1.  0.  1.  2.]
X = 
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
Y = 
[[-2. -2. -2.]
 [-1. -1. -1.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]
 [ 2.  2.  2.]]


In [8]:
Z1 = np.exp(-X**2 - Y**2)
print(Z1)

[[0.00673795 0.01831564 0.00673795]
 [0.13533528 0.36787944 0.13533528]
 [0.36787944 1.         0.36787944]
 [0.13533528 0.36787944 0.13533528]
 [0.00673795 0.01831564 0.00673795]]


In [9]:
Z2 = np.exp(-(X - 1)**2 - (Y - 1)**2)
print(Z2)

[[2.26032941e-06 4.53999298e-05 1.23409804e-04]
 [3.35462628e-04 6.73794700e-03 1.83156389e-02]
 [6.73794700e-03 1.35335283e-01 3.67879441e-01]
 [1.83156389e-02 3.67879441e-01 1.00000000e+00]
 [6.73794700e-03 1.35335283e-01 3.67879441e-01]]


In [10]:
Z = (Z1 - Z2) * 2
print(Z)

[[ 0.01347137  0.03654048  0.01322907]
 [ 0.26999964  0.72228299  0.23403929]
 [ 0.72228299  1.72932943  0.        ]
 [ 0.23403929  0.         -1.72932943]
 [ 0.         -0.23403929 -0.72228299]]
